aggiunto pattern adapter
m1gwings/ing-sw-cheatsheet pull request #18
Opened 2022-12-18 19:14 UTC by francescogemma

Ho iniziato il capitolo sui pattern strutturali e ho aggiunto il pattern adapter (manca ancora il decorator)

2022-12-18 19:14 UTC, francescogemma commented
Controlla in particolare se va bene l'esempio

2022-12-18 19:54 UTC, m1gwings reviewed
Va benissimo, ottimo lavoro! L'unica cosa (se ne hai voglia e soprattutto se hai ancora il progetto dell'immagine de diagramma UML) l'implementazione di Adapter con composizione invece che con ereditarietà è un po' più generale (come hai scritto anche tu Java non supporta ereditarietà multipla). Quindi secondo me è meglio mettere quella invece di questa. Dovrebbe essere sufficiente modificare il diagramma UML (solo la freccia da Adapter ad adaptee) e l'esempio (in teoria basta cambiare qualche linea di codice).

2022-12-18 19:54 UTC, m1gwings commented on design-pattern.md
> +_Attenzione_: Java non supporta l'ereditarietà multipla, quindi, in Java, `Target` è un'interfaccia e `Adapter` la implementa.
Nel caso implementassi la versione con composizione puoi togliere questa riga

2022-12-19 11:24 UTC, m1gwings requested changes
Le ultime due modifichine, lo giuro! 😅

2022-12-19 11:24 UTC, m1gwings commented on design-pattern.md
> +Definiamo anche l'interfaccia `Adaptee` (la libreria esterna), in questo esempio la chiamiamo `FilePrinterLibrary`, che usera un tipo di file diverso da `TextFile` (`File`):
Manca l'accento su "usera"

2022-12-19 11:24 UTC, m1gwings commented on design-pattern.md
> +        FilePrinterLibrary filePrinterLibrary =
Credo convenga trasformare la `filePrinterLibrary` in un attributo, in modo da non doverla creare e distruggere ad ogni `printText`. Inoltre mettendola come attributo è più in linea con la composizione.
Puoi mettere nella classe
```java
public class ... {
    private FilePrinterLibrary filePrinterLibrary = new ...;
   
    ...
}
```

2022-12-19 19:06 UTC, m1gwings requested changes
Grande, ottimo lavoro! Ho aggiunto solo qualche commento per snellire la forma sintattica e rimuovere qualche ripetizione

2022-12-19 19:06 UTC, m1gwings commented on design-pattern.md
> +`FilePrinterLibraryAdapter` implementa `TextPrinter` per poter implementare il metodo `printText()`. Implementiamo il metodo `printText()` istanziando un oggetto `FilePrinterLibrary` e creando un ogg
Cambierei con:
`FilePrinterLibraryAdapter` definisce il metodo `printText()` per poter implementare l'interfaccia `TextPrinter`.

Così evitiamo la ripetizione su implementa.

Nella seconda parte toglierei "istanziando", dato che ora `filePrinterLibrary` è un attributo, e lo sostituirei con "utilizzando".

"può" sarebbe da cambiare con "possiamo"

2022-12-19 19:06 UTC, m1gwings commented on design-pattern.md
> +In questo diagramma, abbiamo `Component` che definisce l'interfaccia che il Client usa, `ConcreteComponent` che implementa `Component`, e `Decorator` che estende `Component` e usa `Component` per agg
Cambierei "aggiungere funzionalità" con "aggiungervi funzionalità" (vi nel senso di aggiungere funzionalità al Component).

Cambierei "aggiungono (ognuno di loro)" con "realizzano (ciascuno)", per dare l'idea che sono i ConcreteDecorator ad implementare concretamente (e quindi a realizzare) la funzionalità aggiuntiva.

2022-12-19 19:06 UTC, m1gwings commented on design-pattern.md
> +Si noti che l'attributo `component` di `Decorator` è di tipo `Component`, e non può essere solo un `ConcreteComponent`, ma anche un altro `Decorator` (`ConcreteDecoratorA` o `ConcreteDecoratorB`), ch
Cambierei "non può essere solo" con "non deve essere per forza" (perchè tecnicamente può essere anche solo un `ConcreteComponent`).

2022-12-19 19:06 UTC, m1gwings commented on design-pattern.md
> +Supponiamo di voler costruire un programma che gestisce un sistema di gestione di un'interfaccia per la visualizzazione di un testo. Il programma deve essere in grado di visualizzare il testo in modo
Toglierei "un sistema di gestione di"

Invertirei "in grassetto" di posizione con "ma anche cambiando il colore del testo".
Così è più chiaro che "in grassetto" è in contrapposizione ad "in modo semplice"

2022-12-19 19:06 UTC, m1gwings commented on design-pattern.md
> +Definiamo anche la classe astratta `Decorator`, in questo esempio la chiamiamo `TextViewDecorator`, che estende `TextView` e usa `TextView` per aggiungere funzionalità:
Toglierei "anche" per evitare la ripetizione con la frase prima

2022-12-19 19:06 UTC, m1gwings commented on design-pattern.md
> +Definiamo anche le classi `ConcreteDecoratorA`, in questo esempio la chiamiamo `ColoredTextView`; e `ConcreteDecoratorB`, in questo esempio la chiamiamo `BoldTextView`, che estendono `TextViewDecorat
Stessa storia per questo "anche"

Toglierei "e aggiungono (ognuno di loro) una funzionalità", tanto l'abbiamo già spiegato nell'introduzione

2022-12-19 19:17 UTC, francescogemma commented
minchia hai fatto l'analisi grammaticale

2022-12-19 19:30 UTC, merged