aggiunto testing-strutturale
m1gwings/ing-sw-cheatsheet pull request #29
Opened 2022-12-28 11:29 UTC by francescogemma

2022-12-28 19:53 UTC, francescogemma commented
dovrei aver fixato il bug dell'indice, l'ho messo in questa pull request direttamente

2022-12-29 17:30 UTC, m1gwings requested changes

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +Dobbiamo selezionare dei casi di testi in modo che ogni istruzione venga eseguita almeno una volta.
Credo ci sia un typo:
testi -> test

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +Il **testing strutturale** tiene conto della struttura interna del programma con l'obiettivo di sollecitare tutte le parti del programma.
Cambierei:
sollecitare tutte le parti del programma -> sollecitarne tutte le parti
così evitiamo la ripetizione su programma

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +Si vuole coprire tutte le possibili _diramazioni_ del programma. per fare ciò è utile costruire il **control flow graph** (o **CFG**) del programma in cui si evidenziono proprio tutte le diramazioni.
Mi sa che manca la maiuscola su
per

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +Ogni arco rappresenta una possibile diramazione. Si noti che ogni `if` e `while` sono rappresentati da due archi, uno per il caso `true` e uno per il caso `false` (anche se ad esempio il ramo `else`
Credo vada cambiato:
sono rappresentati -> è rappresentato
perché ogni è singolare

Oppure si può scirvere
... gli `if` e `while` sono rappresentati ciascuno da due archi ...

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +Il criterio **edge coverage** vuole che ogni arco del CFG venga eseguito almeno una volta. Per fare ciò possiamo scegliere i seguenti casi di test:
Cambierei:
vuole -> richiede

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +- `n = -1` per eseguire solo l'arco `n < 0` (e finire il programma)
Cambierei:
finire il programma -> giungere alla terminazione del programma

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +L’insieme dei casi di test deve essere definito in modo che ogni ramo del CFG venga attraversato almeno una volta e con **tutti i possibili valori** nelle sottoespressioni che compaiono nelle condizi
Cambierei:
con **tutti i possibili valori** nelle sottoespressioni che compaiono nelle condizioni composte -> sollecitando tutti i valori di verità delle sottoespressioni che compaiono nelle condizioni composte, tenendo conto della _short circuit evaluation_

Perché ad esempio, nello snippet di codice sotto "**tutti i possibili valori** nelle sottoespressioni" sono 4 (la prima vera e la seconda falsa, il viceversa, entrambe vere, entrambe false) ma ne bastano 3 per sollecitare tutti i valori di verità

Poi più in là pensavo di rimetterci mano a questa parte proprio per rendere più chiara questa cosa, perché anche come l'ha spiegata San Pietro non mi convince, però per ora va benissimo così, poi se ho tempo me ne occuperò io alla fine

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +Si può entrare nel ramo `if` nei seguenti modi: `x = 0, y <= 0` e `x != 0, y > 0`
Nel primo caso metterei `x == 0`, `y` qualsiasi.
Sempre per evidenziare la roba della _short circuit evaluation_

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +L’insieme dei casi di test deve garantire che ogni possibile cammino (o percorso) che porti dal nodo iniziale al nodo finale del CFG sia percorso almeno una volta.
Cambierei il secondo percorso (il participio passato di percorrere, non il sostantivo):
percorso -> attraversato (o sollecitato, come preferisci)
così evitiamo la ripetizione su percorso

2022-12-29 17:30 UTC, m1gwings commented on testing.md
> +_Attenzione_: il numero di volte in qui si esegue un ciclo (un autoanello nel CFG) è rilevante. Perciò, se un ciclo può essere eseguito "infinite" volte, allora il criterio di copertura dei cammini n
Credo che vada cambiato:
qui -> cui

2022-12-29 17:44 UTC, merged